name: Build ProjectService

on:
  push:
    branches: [ master ]
    paths:
      - 'ProjectService/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'ProjectService/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./ProjectService/ProjectService.sln

    - name: Build
      run: dotnet build ./ProjectService/ProjectService.sln --no-restore -c Release

    - name: Test
      run: dotnet test ./ProjectService/ProjectService.sln --no-build -c Release --verbosity normal

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ProjectService/src/ProjectService.Api
        push: true
        tags: dibabasu/projectservice:latest